/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EduConnectCertificates } from "./EduConnectCertificates";
export * as factories from "./factories";
export { EduConnectCertificates__factory } from "./factories/EduConnectCertificates__factory";
